insert into Products (Name, Price, Status) values ('V8 Splash Strawberry Kiwi', 2695807, 0);
insert into Products (Name, Price, Status) values ('Bread - Olive Dinner Roll', 824087, 0);
insert into Products (Name, Price, Status) values ('Foil Wrap', 6447871, 1);
insert into Products (Name, Price, Status) values ('Vinegar - Champagne', 9002662, 1);
insert into Products (Name, Price, Status) values ('Truffle - Peelings', 1564264, 0);
insert into Products (Name, Price, Status) values ('Mcguinness - Blue Curacao', 3479149, 0);
insert into Products (Name, Price, Status) values ('Lentils - Green, Dry', 6489591, 0);
insert into Products (Name, Price, Status) values ('Gatorade - Orange', 9447285, 0);
insert into Products (Name, Price, Status) values ('Brocolinni - Gaylan, Chinese', 3231342, 1);
insert into Products (Name, Price, Status) values ('Venison - Striploin', 8161588, 1);
insert into Products (Name, Price, Status) values ('Beef Dry Aged Tenderloin Aaa', 1993795, 1);
insert into Products (Name, Price, Status) values ('Quinoa', 3450975, 0);
insert into Products (Name, Price, Status) values ('Urban Zen Drinks', 3476355, 0);
insert into Products (Name, Price, Status) values ('Wine - Jafflin Bourgongone', 6182699, 1);
insert into Products (Name, Price, Status) values ('Tea - Decaf 1 Cup', 1059323, 1);
insert into Products (Name, Price, Status) values ('Beer - Fruli', 1031524, 1);
insert into Products (Name, Price, Status) values ('Coffee - Espresso', 8774775, 0);
insert into Products (Name, Price, Status) values ('Towels - Paper / Kraft', 3316683, 1);
insert into Products (Name, Price, Status) values ('Pasta - Rotini, Colour, Dry', 6336835, 0);
insert into Products (Name, Price, Status) values ('Wine - Guy Sage Touraine', 4665083, 0);
insert into Products (Name, Price, Status) values ('Sea Bass - Whole', 4224983, 1);
insert into Products (Name, Price, Status) values ('Gatorade - Xfactor Berry', 9988969, 1);
insert into Products (Name, Price, Status) values ('Lemonade - Island Tea, 591 Ml', 8651151, 0);
insert into Products (Name, Price, Status) values ('Lid Coffee Cup 8oz Blk', 8325351, 0);
insert into Products (Name, Price, Status) values ('Island Oasis - Mango Daiquiri', 8007813, 1);
insert into Products (Name, Price, Status) values ('Water - Evian 355 Ml', 2195728, 0);
insert into Products (Name, Price, Status) values ('Cheese - Cottage Cheese', 2645637, 0);
insert into Products (Name, Price, Status) values ('Oil - Sunflower', 4345884, 1);
insert into Products (Name, Price, Status) values ('Tea - Herbal - 6 Asst', 3575290, 1);
insert into Products (Name, Price, Status) values ('Apple - Granny Smith', 7094850, 0);
insert into Products (Name, Price, Status) values ('Sherbet - Raspberry', 5460946, 0);
insert into Products (Name, Price, Status) values ('Towel - Roll White', 7757529, 1);
insert into Products (Name, Price, Status) values ('Table Cloth 54x72 White', 8630210, 1);
insert into Products (Name, Price, Status) values ('Remy Red Berry Infusion', 6878395, 1);
insert into Products (Name, Price, Status) values ('V8 - Berry Blend', 6607065, 0);
insert into Products (Name, Price, Status) values ('Wine - White, Riesling, Semi - Dry', 3894724, 1);
insert into Products (Name, Price, Status) values ('Duck - Fat', 5338619, 1);
insert into Products (Name, Price, Status) values ('Soup - Knorr, Veg / Beef', 3597725, 1);
insert into Products (Name, Price, Status) values ('Wine - Zonnebloem Pinotage', 7047299, 0);
insert into Products (Name, Price, Status) values ('Water - Perrier', 9316099, 0);
insert into Products (Name, Price, Status) values ('Brandy - Orange, Mc Guiness', 6058901, 0);
insert into Products (Name, Price, Status) values ('Swiss Chard', 9027543, 0);
insert into Products (Name, Price, Status) values ('Silicone Parch. 16.3x24.3', 4293737, 0);
insert into Products (Name, Price, Status) values ('Country Roll', 8455459, 1);
insert into Products (Name, Price, Status) values ('Spaghetti Squash', 969703, 1);
insert into Products (Name, Price, Status) values ('Ecolab - Hand Soap Form Antibac', 393377, 1);
insert into Products (Name, Price, Status) values ('Lobster - Cooked', 4356623, 0);
insert into Products (Name, Price, Status) values ('Long Island Ice Tea', 5940907, 1);
insert into Products (Name, Price, Status) values ('Higashimaru Usukuchi Soy', 5893124, 0);
insert into Products (Name, Price, Status) values ('Oil - Safflower', 7619585, 1);
insert into Products (Name, Price, Status) values ('Bread - Malt', 3916614, 0);
insert into Products (Name, Price, Status) values ('Wine - Peller Estates Late', 9663023, 1);
insert into Products (Name, Price, Status) values ('Sterno - Chafing Dish Fuel', 3919201, 0);
insert into Products (Name, Price, Status) values ('Beef - Top Butt Aaa', 3889362, 0);
insert into Products (Name, Price, Status) values ('Poppy Seed', 4526752, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Lambs Mash', 3120549, 1);
insert into Products (Name, Price, Status) values ('Cabbage - Green', 2110909, 0);
insert into Products (Name, Price, Status) values ('Sugar - Splenda Sweetener', 5272896, 1);
insert into Products (Name, Price, Status) values ('Potatoes - Parissienne', 7425222, 1);
insert into Products (Name, Price, Status) values ('Lamb Rack Frenched Australian', 6930338, 0);
insert into Products (Name, Price, Status) values ('Wine - Prem Select Charddonany', 1850844, 0);
insert into Products (Name, Price, Status) values ('Lamb - Rack', 7667558, 1);
insert into Products (Name, Price, Status) values ('Soupcontfoam16oz 116con', 2591996, 1);
insert into Products (Name, Price, Status) values ('Juice - Lagoon Mango', 9605381, 0);
insert into Products (Name, Price, Status) values ('Vodka - Hot, Lnferno', 1587653, 0);
insert into Products (Name, Price, Status) values ('Salmon - Whole, 4 - 6 Pounds', 9336488, 0);
insert into Products (Name, Price, Status) values ('Spinach - Packaged', 755168, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Pistoles, White', 9692681, 1);
insert into Products (Name, Price, Status) values ('Wine - Pinot Noir Latour', 9239623, 1);
insert into Products (Name, Price, Status) values ('Wine - Puligny Montrachet A.', 7956553, 1);
insert into Products (Name, Price, Status) values ('Yogurt - Peach, 175 Gr', 750380, 1);
insert into Products (Name, Price, Status) values ('Wine - Valpolicella Masi', 9472597, 1);
insert into Products (Name, Price, Status) values ('Fib N9 - Prague Powder', 4501523, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Semi Sweet', 4871783, 1);
insert into Products (Name, Price, Status) values ('Sauce - Gravy, Au Jus, Mix', 6847514, 0);
insert into Products (Name, Price, Status) values ('Quinoa', 181815, 0);
insert into Products (Name, Price, Status) values ('Wine - Ej Gallo Sierra Valley', 9620364, 1);
insert into Products (Name, Price, Status) values ('Bagel - Whole White Sesame', 1777352, 0);
insert into Products (Name, Price, Status) values ('Wine - White Cab Sauv.on', 4113293, 0);
insert into Products (Name, Price, Status) values ('Muffin Mix - Corn Harvest', 2615131, 0);
insert into Products (Name, Price, Status) values ('Nut - Almond, Blanched, Sliced', 2379758, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Sugar Free Semi Choc', 7459948, 1);
insert into Products (Name, Price, Status) values ('Soup - Campbells Tomato Ravioli', 8211974, 0);
insert into Products (Name, Price, Status) values ('Vol Au Vents', 1765885, 0);
insert into Products (Name, Price, Status) values ('Paper - Brown Paper Mini Cups', 7266277, 0);
insert into Products (Name, Price, Status) values ('Barley - Pearl', 6056228, 0);
insert into Products (Name, Price, Status) values ('Asparagus - Green, Fresh', 2016180, 1);
insert into Products (Name, Price, Status) values ('Wine - Magnotta - Bel Paese White', 4727000, 1);
insert into Products (Name, Price, Status) values ('Soy Protein', 8490403, 1);
insert into Products (Name, Price, Status) values ('Shrimp - 16 - 20 Cooked, Peeled', 5616267, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Crimini', 3377441, 0);
insert into Products (Name, Price, Status) values ('Duck - Whole', 8015362, 1);
insert into Products (Name, Price, Status) values ('Pastry - Cheese Baked Scones', 9338730, 1);
insert into Products (Name, Price, Status) values ('Bay Leaf Ground', 9154735, 0);
insert into Products (Name, Price, Status) values ('True - Vue Containers', 5934323, 0);
insert into Products (Name, Price, Status) values ('Towels - Paper / Kraft', 6749894, 0);
insert into Products (Name, Price, Status) values ('Phyllo Dough', 5716643, 0);
insert into Products (Name, Price, Status) values ('Ice Cream Bar - Hagen Daz', 9692803, 1);
insert into Products (Name, Price, Status) values ('Cheese - Asiago', 7326222, 1);
insert into Products (Name, Price, Status) values ('Flour - Corn, Fine', 2009901, 1);
insert into Products (Name, Price, Status) values ('Pear - Packum', 8215945, 0);
insert into Products (Name, Price, Status) values ('Beer - Paulaner Hefeweisse', 1483480, 0);
insert into Products (Name, Price, Status) values ('Carrots - Purple, Organic', 8991371, 1);
insert into Products (Name, Price, Status) values ('Yoghurt Tubes', 7306136, 0);
insert into Products (Name, Price, Status) values ('Strawberries - California', 4763210, 0);
insert into Products (Name, Price, Status) values ('Cheese - Valancey', 6455494, 0);
insert into Products (Name, Price, Status) values ('Beef - Chuck, Boneless', 4586152, 1);
insert into Products (Name, Price, Status) values ('Pasta - Tortellini, Fresh', 7831722, 1);
insert into Products (Name, Price, Status) values ('Pie Filling - Apple', 8656338, 0);
insert into Products (Name, Price, Status) values ('Doilies - 10, Paper', 7225274, 0);
insert into Products (Name, Price, Status) values ('Veal Inside - Provimi', 3472069, 0);
insert into Products (Name, Price, Status) values ('Longos - Grilled Veg Sandwiches', 6269384, 0);
insert into Products (Name, Price, Status) values ('Soup - Campbells, Minestrone', 9667158, 0);
insert into Products (Name, Price, Status) values ('Ecolab - Power Fusion', 7304941, 0);
insert into Products (Name, Price, Status) values ('Fish - Artic Char, Cold Smoked', 603388, 0);
insert into Products (Name, Price, Status) values ('Tomato - Plum With Basil', 513179, 0);
insert into Products (Name, Price, Status) values ('Vinegar - White', 1622642, 0);
insert into Products (Name, Price, Status) values ('Cheese - St. Paulin', 2415722, 1);
insert into Products (Name, Price, Status) values ('Anisette - Mcguiness', 2841216, 1);
insert into Products (Name, Price, Status) values ('Cookies - Englishbay Oatmeal', 4641936, 0);
insert into Products (Name, Price, Status) values ('Cheese Cloth', 3304858, 0);
insert into Products (Name, Price, Status) values ('Chicken - Leg, Fresh', 224802, 0);
insert into Products (Name, Price, Status) values ('Grapes - Black', 9894552, 1);
insert into Products (Name, Price, Status) values ('Basil - Fresh', 2671071, 0);
insert into Products (Name, Price, Status) values ('Rolled Oats', 2423491, 1);
insert into Products (Name, Price, Status) values ('Cake Slab', 1871230, 0);
insert into Products (Name, Price, Status) values ('Creamers - 10%', 3622498, 0);
insert into Products (Name, Price, Status) values ('Beef - Short Loin', 6399419, 1);
insert into Products (Name, Price, Status) values ('Lamb - Whole Head Off,nz', 8146622, 0);
insert into Products (Name, Price, Status) values ('Wine - Fino Tio Pepe Gonzalez', 7607759, 0);
insert into Products (Name, Price, Status) values ('Sugar - Sweet N Low, Individual', 3968257, 0);
insert into Products (Name, Price, Status) values ('Cumin - Ground', 4639327, 1);
insert into Products (Name, Price, Status) values ('Spice - Montreal Steak Spice', 7487406, 0);
insert into Products (Name, Price, Status) values ('Pastry - Choclate Baked', 1942899, 1);
insert into Products (Name, Price, Status) values ('Syrup - Chocolate', 444889, 0);
insert into Products (Name, Price, Status) values ('Bagel - Everything', 3380904, 1);
insert into Products (Name, Price, Status) values ('Blackberries', 2124236, 0);
insert into Products (Name, Price, Status) values ('Squid - Tubes / Tenticles 10/20', 1901229, 0);
insert into Products (Name, Price, Status) values ('Wine - White, Pelee Island', 8275588, 0);
insert into Products (Name, Price, Status) values ('Jam - Raspberry,jar', 1872352, 1);
insert into Products (Name, Price, Status) values ('Pork - Liver', 1151054, 0);
insert into Products (Name, Price, Status) values ('Cookies - Englishbay Wht', 8621445, 0);
insert into Products (Name, Price, Status) values ('Pie Shell - 5', 5873768, 0);
insert into Products (Name, Price, Status) values ('Sauce - Balsamic Viniagrette', 6412854, 0);
insert into Products (Name, Price, Status) values ('Tamarind Paste', 8936387, 0);
insert into Products (Name, Price, Status) values ('Halibut - Steaks', 2041719, 0);
insert into Products (Name, Price, Status) values ('Tuna - Fresh', 9603102, 0);
insert into Products (Name, Price, Status) values ('Vermouth - White, Cinzano', 6403633, 1);
insert into Products (Name, Price, Status) values ('Wine - Alicanca Vinho Verde', 1204113, 0);
insert into Products (Name, Price, Status) values ('Coffee Cup 16oz Foam', 5491002, 1);
insert into Products (Name, Price, Status) values ('Soup - Campbells Mac N Cheese', 9480226, 1);
insert into Products (Name, Price, Status) values ('Cheese - Ermite Bleu', 3428520, 0);
insert into Products (Name, Price, Status) values ('Flour - Pastry', 1091932, 1);
insert into Products (Name, Price, Status) values ('Vol Au Vents', 4340230, 0);
insert into Products (Name, Price, Status) values ('Sugar Thermometer', 3148628, 1);
insert into Products (Name, Price, Status) values ('Chef Hat 25cm', 1500263, 1);
insert into Products (Name, Price, Status) values ('Longos - Grilled Veg Sandwiches', 5929325, 1);
insert into Products (Name, Price, Status) values ('Apples - Sliced / Wedge', 476360, 1);
insert into Products (Name, Price, Status) values ('Mix - Cappucino Cocktail', 4605511, 1);
insert into Products (Name, Price, Status) values ('Longos - Chicken Curried', 7272142, 0);
insert into Products (Name, Price, Status) values ('Scallop - St. Jaques', 3448494, 1);
insert into Products (Name, Price, Status) values ('Pecan Raisin - Tarts', 1892474, 0);
insert into Products (Name, Price, Status) values ('Cheese - Parmigiano Reggiano', 5835719, 1);
insert into Products (Name, Price, Status) values ('Tofu - Firm', 1973860, 1);
insert into Products (Name, Price, Status) values ('Oil - Olive Bertolli', 9205092, 1);
insert into Products (Name, Price, Status) values ('Cabbage Roll', 9588179, 0);
insert into Products (Name, Price, Status) values ('The Pop Shoppe - Grape', 9162105, 1);
insert into Products (Name, Price, Status) values ('Wine - Prem Select Charddonany', 1296261, 0);
insert into Products (Name, Price, Status) values ('White Baguette', 157822, 1);
insert into Products (Name, Price, Status) values ('Marjoram - Dried, Rubbed', 9533064, 0);
insert into Products (Name, Price, Status) values ('Sauce - Oyster', 9818924, 1);
insert into Products (Name, Price, Status) values ('Broom And Broom Rack White', 849231, 0);
insert into Products (Name, Price, Status) values ('Oregano - Fresh', 1390769, 1);
insert into Products (Name, Price, Status) values ('Soup Campbells Mexicali Tortilla', 5982648, 0);
insert into Products (Name, Price, Status) values ('Chocolate - Liqueur Cups With Foil', 6869556, 0);
insert into Products (Name, Price, Status) values ('The Pop Shoppe - Black Cherry', 5368112, 1);
insert into Products (Name, Price, Status) values ('Beef - Inside Round', 4062263, 1);
insert into Products (Name, Price, Status) values ('Lettuce Romaine Chopped', 8090817, 0);
insert into Products (Name, Price, Status) values ('Scallop - St. Jaques', 5240080, 1);
insert into Products (Name, Price, Status) values ('Bok Choy - Baby', 5576853, 0);
insert into Products (Name, Price, Status) values ('Wine - Chateau Timberlay', 4536155, 1);
insert into Products (Name, Price, Status) values ('Wine - Acient Coast Caberne', 9484089, 0);
insert into Products (Name, Price, Status) values ('Beef - Bresaola', 2767565, 1);
insert into Products (Name, Price, Status) values ('Rice - 7 Grain Blend', 9270568, 1);
insert into Products (Name, Price, Status) values ('Sprouts - Alfalfa', 8813998, 1);
insert into Products (Name, Price, Status) values ('Kolrabi', 4340806, 1);
insert into Products (Name, Price, Status) values ('Jack Daniels', 1853079, 1);
insert into Products (Name, Price, Status) values ('Chips - Doritos', 4490065, 1);
insert into Products (Name, Price, Status) values ('Latex Rubber Gloves Size 9', 3350515, 1);
insert into Products (Name, Price, Status) values ('Beer - Alexander Kieths, Pale Ale', 8276916, 0);
insert into Products (Name, Price, Status) values ('Scallops - 20/30', 5322469, 1);
insert into Products (Name, Price, Status) values ('Wine - German Riesling', 4019983, 0);
insert into Products (Name, Price, Status) values ('Chicken Breast Halal', 4789243, 0);
insert into Products (Name, Price, Status) values ('Flour - Chickpea', 9746651, 0);
insert into Products (Name, Price, Status) values ('Nantucket - Pomegranate Pear', 6265348, 1);
insert into Products (Name, Price, Status) values ('Island Oasis - Strawberry', 2779712, 1);
insert into Products (Name, Price, Status) values ('Dried Cranberries', 14310, 0);
insert into Products (Name, Price, Status) values ('Cookie Choc', 1402295, 0);
insert into Products (Name, Price, Status) values ('Potato - Sweet', 7383325, 0);
insert into Products (Name, Price, Status) values ('Oil - Pumpkinseed', 6506011, 1);
insert into Products (Name, Price, Status) values ('Noodles - Steamed Chow Mein', 4641496, 0);
insert into Products (Name, Price, Status) values ('Bread - Pain Au Liat X12', 7897281, 1);
insert into Products (Name, Price, Status) values ('Mustard - Dry, Powder', 9586232, 0);
insert into Products (Name, Price, Status) values ('Apple - Royal Gala', 4105013, 0);
insert into Products (Name, Price, Status) values ('Ecolab - Mikroklene 4/4 L', 5640062, 0);
insert into Products (Name, Price, Status) values ('Chinese Foods - Plain Fried Rice', 6560868, 1);
insert into Products (Name, Price, Status) values ('Cloves - Whole', 2747196, 0);
insert into Products (Name, Price, Status) values ('Hummus - Spread', 433021, 0);
insert into Products (Name, Price, Status) values ('Chinese Foods - Cantonese', 3531540, 0);
insert into Products (Name, Price, Status) values ('Gelatine Leaves - Bulk', 3004575, 1);
insert into Products (Name, Price, Status) values ('Ecolab - Ster Bac', 110575, 0);
insert into Products (Name, Price, Status) values ('Capers - Pickled', 7598036, 0);
insert into Products (Name, Price, Status) values ('Beef - Prime Rib Aaa', 748778, 0);
insert into Products (Name, Price, Status) values ('Wine - Chablis J Moreau Et Fils', 8621959, 0);
insert into Products (Name, Price, Status) values ('Oil - Coconut', 8084477, 1);
insert into Products (Name, Price, Status) values ('Bread - Sour Sticks With Onion', 1200371, 1);
insert into Products (Name, Price, Status) values ('Buffalo - Striploin', 191376, 0);
insert into Products (Name, Price, Status) values ('Basil - Seedlings Cookstown', 4911932, 1);
insert into Products (Name, Price, Status) values ('Stock - Beef, White', 4322222, 0);
insert into Products (Name, Price, Status) values ('Jolt Cola - Red Eye', 3119882, 0);
insert into Products (Name, Price, Status) values ('Wine - Puligny Montrachet A.', 1974899, 0);
insert into Products (Name, Price, Status) values ('Eggs - Extra Large', 4108707, 1);
insert into Products (Name, Price, Status) values ('Soup - Cream Of Broccoli', 6629715, 0);
insert into Products (Name, Price, Status) values ('Table Cloth 90x90 White', 5874111, 1);
insert into Products (Name, Price, Status) values ('Crackers - Melba Toast', 6794452, 1);
insert into Products (Name, Price, Status) values ('Rabbit - Legs', 7798981, 1);
insert into Products (Name, Price, Status) values ('Juice - Cranberry, 341 Ml', 9405055, 1);
insert into Products (Name, Price, Status) values ('Fib N9 - Prague Powder', 8640553, 1);
insert into Products (Name, Price, Status) values ('Pears - Bartlett', 6396344, 1);
insert into Products (Name, Price, Status) values ('Straws - Cocktale', 6202055, 0);
insert into Products (Name, Price, Status) values ('Glass Clear 8 Oz', 8248619, 1);
insert into Products (Name, Price, Status) values ('Glaze - Apricot', 131269, 0);
insert into Products (Name, Price, Status) values ('Pea - Snow', 8838922, 1);
insert into Products (Name, Price, Status) values ('Soap - Hand Soap', 1292390, 1);
insert into Products (Name, Price, Status) values ('Bread Foccacia Whole', 5672387, 1);
insert into Products (Name, Price, Status) values ('Mint - Fresh', 5019694, 1);
insert into Products (Name, Price, Status) values ('Sauce - Cranberry', 5998866, 1);
insert into Products (Name, Price, Status) values ('Oil - Avocado', 6135692, 1);
insert into Products (Name, Price, Status) values ('Plate Foam Laminated 9in Blk', 3945605, 1);
insert into Products (Name, Price, Status) values ('Asparagus - White, Fresh', 1759840, 1);
insert into Products (Name, Price, Status) values ('Tea - Herbal Sweet Dreams', 5723511, 1);
insert into Products (Name, Price, Status) values ('Parsley Italian - Fresh', 5855235, 1);
insert into Products (Name, Price, Status) values ('Trueblue - Blueberry Cranberry', 7002842, 1);
insert into Products (Name, Price, Status) values ('Juice - Cranberry 284ml', 3149949, 1);
insert into Products (Name, Price, Status) values ('Wine - Rioja Campo Viejo', 3549647, 1);
insert into Products (Name, Price, Status) values ('Oneshot Automatic Soap System', 2822653, 1);
insert into Products (Name, Price, Status) values ('Aspic - Clear', 5845674, 0);
insert into Products (Name, Price, Status) values ('Broom - Push', 8884189, 1);
insert into Products (Name, Price, Status) values ('Pork - Backfat', 713345, 0);
insert into Products (Name, Price, Status) values ('Nut - Peanut, Roasted', 6587053, 0);
insert into Products (Name, Price, Status) values ('Rambutan', 6496784, 1);
insert into Products (Name, Price, Status) values ('Salt - Rock, Course', 1707550, 0);
insert into Products (Name, Price, Status) values ('Cassis', 6989924, 1);
insert into Products (Name, Price, Status) values ('Towel Dispenser', 1440686, 0);
insert into Products (Name, Price, Status) values ('Lemon Balm - Fresh', 476231, 1);
insert into Products (Name, Price, Status) values ('Tray - 12in Rnd Blk', 6770939, 1);
insert into Products (Name, Price, Status) values ('Galliano', 5832003, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Mini Greens, Whole', 4023540, 1);
insert into Products (Name, Price, Status) values ('Truffle Shells - Semi - Sweet', 5617748, 1);
insert into Products (Name, Price, Status) values ('Sour Cream', 8713989, 0);
insert into Products (Name, Price, Status) values ('Milkettes - 2%', 1220548, 1);
insert into Products (Name, Price, Status) values ('Arizona - Green Tea', 3287221, 1);
insert into Products (Name, Price, Status) values ('Garbage Bag - Clear', 7956040, 0);
insert into Products (Name, Price, Status) values ('Chicken - Diced, Cooked', 1225922, 0);
insert into Products (Name, Price, Status) values ('Nut - Pecan, Halves', 9131745, 1);
insert into Products (Name, Price, Status) values ('Bread - Raisin Walnut Pull', 2885707, 1);
insert into Products (Name, Price, Status) values ('Cake - Box Window 10x10x2.5', 6598519, 1);
insert into Products (Name, Price, Status) values ('Oregano - Fresh', 7495202, 1);
insert into Products (Name, Price, Status) values ('Piping Jelly - All Colours', 216095, 1);
insert into Products (Name, Price, Status) values ('Marjoram - Dried, Rubbed', 6681966, 0);
insert into Products (Name, Price, Status) values ('Duck - Fat', 1631298, 1);
insert into Products (Name, Price, Status) values ('Mints - Striped Red', 5248434, 0);
insert into Products (Name, Price, Status) values ('Sobe - Tropical Energy', 1040375, 0);
insert into Products (Name, Price, Status) values ('Flower - Dish Garden', 1179824, 1);
insert into Products (Name, Price, Status) values ('Rice - Basmati', 7791811, 1);
insert into Products (Name, Price, Status) values ('Bread - Dark Rye', 5006352, 0);
insert into Products (Name, Price, Status) values ('Pepper - Red Chili', 8296547, 1);
insert into Products (Name, Price, Status) values ('Mountain Dew', 4043331, 1);
insert into Products (Name, Price, Status) values ('Bread - Bagels, Plain', 4198520, 1);
insert into Products (Name, Price, Status) values ('Jack Daniels', 8669645, 1);
insert into Products (Name, Price, Status) values ('Thyme - Fresh', 7363807, 0);
insert into Products (Name, Price, Status) values ('Coffee Cup 12oz 5342cd', 9369655, 0);
insert into Products (Name, Price, Status) values ('Pasta - Fusili, Dry', 2630776, 0);
insert into Products (Name, Price, Status) values ('Cilantro / Coriander - Fresh', 1955969, 0);
insert into Products (Name, Price, Status) values ('Nantucket - 518ml', 4404433, 1);
insert into Products (Name, Price, Status) values ('Cake Circle, Foil, Scallop', 3269908, 0);
insert into Products (Name, Price, Status) values ('Fond - Neutral', 5067091, 1);
insert into Products (Name, Price, Status) values ('Orange Roughy 4/6 Oz', 5859054, 1);
insert into Products (Name, Price, Status) values ('Tart - Pecan Butter Squares', 5062691, 1);
insert into Products (Name, Price, Status) values ('Creme De Cacao White', 5044029, 1);
insert into Products (Name, Price, Status) values ('Corn Shoots', 166549, 0);
insert into Products (Name, Price, Status) values ('Pork - Ground', 2222955, 1);
insert into Products (Name, Price, Status) values ('Beef - Roasted, Cooked', 6518791, 1);
insert into Products (Name, Price, Status) values ('Gherkin', 6142255, 1);
insert into Products (Name, Price, Status) values ('V8 - Tropical Blend', 268779, 0);
insert into Products (Name, Price, Status) values ('Beef - Ox Tongue', 9263046, 1);
insert into Products (Name, Price, Status) values ('Dasheen', 999098, 1);
insert into Products (Name, Price, Status) values ('Flour - Buckwheat, Dark', 2848030, 1);
insert into Products (Name, Price, Status) values ('Wine - Ruffino Chianti Classico', 1070495, 1);
insert into Products (Name, Price, Status) values ('Bay Leaf Fresh', 6385495, 0);
insert into Products (Name, Price, Status) values ('Table Cloth 90x90 Colour', 4844984, 0);
insert into Products (Name, Price, Status) values ('Snails - Large Canned', 9455414, 1);
insert into Products (Name, Price, Status) values ('Sauce - Soy Low Sodium - 3.87l', 5893199, 0);
insert into Products (Name, Price, Status) values ('Chicken - Wings, Tip Off', 4208363, 1);
insert into Products (Name, Price, Status) values ('Flour - Semolina', 5660980, 1);
insert into Products (Name, Price, Status) values ('Bread - Bistro Sour', 1628343, 0);
insert into Products (Name, Price, Status) values ('Peas - Pigeon, Dry', 6473454, 1);
insert into Products (Name, Price, Status) values ('Pears - Bartlett', 815994, 1);
insert into Products (Name, Price, Status) values ('Rum - White, Gg White', 9880136, 0);
insert into Products (Name, Price, Status) values ('Broom - Corn', 9378330, 0);
insert into Products (Name, Price, Status) values ('Lobak', 8508470, 1);
insert into Products (Name, Price, Status) values ('Guava', 3733889, 1);
insert into Products (Name, Price, Status) values ('Cookies Almond Hazelnut', 3088066, 1);
insert into Products (Name, Price, Status) values ('Glucose', 6311152, 1);
insert into Products (Name, Price, Status) values ('Soap - Mr.clean Floor Soap', 6544524, 0);
insert into Products (Name, Price, Status) values ('Oyster - In Shell', 5015282, 0);
insert into Products (Name, Price, Status) values ('Juice - Clam, 46 Oz', 231982, 0);
insert into Products (Name, Price, Status) values ('Instant Coffee', 9169381, 1);
insert into Products (Name, Price, Status) values ('Island Oasis - Sweet And Sour Mix', 4280984, 1);
insert into Products (Name, Price, Status) values ('Shrimp - 100 / 200 Cold Water', 6482627, 1);
insert into Products (Name, Price, Status) values ('Cakes Assorted', 2402080, 0);
insert into Products (Name, Price, Status) values ('Butter - Unsalted', 7960022, 1);
insert into Products (Name, Price, Status) values ('Squash - Sunburst', 8647471, 0);
insert into Products (Name, Price, Status) values ('Sugar - Cubes', 6173565, 1);
insert into Products (Name, Price, Status) values ('Sausage - Liver', 3946594, 1);
insert into Products (Name, Price, Status) values ('Maintenance Removal Charge', 6802632, 1);
insert into Products (Name, Price, Status) values ('Garlic - Elephant', 7978009, 1);
insert into Products (Name, Price, Status) values ('Flour - Masa De Harina Mexican', 3630834, 0);
insert into Products (Name, Price, Status) values ('Tea - Green', 5495148, 1);
insert into Products (Name, Price, Status) values ('Tarts Assorted', 8771624, 0);
insert into Products (Name, Price, Status) values ('Sour Puss - Tangerine', 4514238, 0);
insert into Products (Name, Price, Status) values ('Beer - Blue Light', 5933165, 1);
insert into Products (Name, Price, Status) values ('Fish - Soup Base, Bouillon', 2154570, 1);
insert into Products (Name, Price, Status) values ('Tarragon - Primerba, Paste', 8890632, 0);
insert into Products (Name, Price, Status) values ('Currants', 4286884, 1);
insert into Products (Name, Price, Status) values ('Vinegar - White Wine', 9444736, 1);
insert into Products (Name, Price, Status) values ('Vinegar - Sherry', 7076184, 0);
insert into Products (Name, Price, Status) values ('Wine - Saint - Bris 2002, Sauv', 2409761, 0);
insert into Products (Name, Price, Status) values ('Pie Filling - Pumpkin', 8093771, 0);
insert into Products (Name, Price, Status) values ('Langers - Mango Nectar', 6486025, 0);
insert into Products (Name, Price, Status) values ('Salami - Genova', 5493813, 0);
insert into Products (Name, Price, Status) values ('Stock - Chicken, White', 9806156, 1);
insert into Products (Name, Price, Status) values ('Broom - Angled', 8378793, 0);
insert into Products (Name, Price, Status) values ('Flour - Fast / Rapid', 9606949, 0);
insert into Products (Name, Price, Status) values ('V8 - Vegetable Cocktail', 4688235, 0);
insert into Products (Name, Price, Status) values ('Sproutsmustard Cress', 7577015, 0);
insert into Products (Name, Price, Status) values ('Kiwi Gold Zespri', 6662108, 1);
insert into Products (Name, Price, Status) values ('Dome Lid Clear P92008h', 8855770, 1);
insert into Products (Name, Price, Status) values ('Cheese - Gorgonzola', 1405061, 0);
insert into Products (Name, Price, Status) values ('Quail - Whole, Bone - In', 1612258, 1);
insert into Products (Name, Price, Status) values ('Juice - Grape, White', 2328819, 0);
insert into Products (Name, Price, Status) values ('Oil - Pumpkinseed', 7792811, 0);
insert into Products (Name, Price, Status) values ('Cheese - Mix', 6010206, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Dark Callets', 6638818, 0);
insert into Products (Name, Price, Status) values ('Grapes - Green', 8907961, 0);
insert into Products (Name, Price, Status) values ('Sauce - Hp', 4510382, 1);
insert into Products (Name, Price, Status) values ('Sauce - Hp', 9923048, 0);
insert into Products (Name, Price, Status) values ('Raspberries - Frozen', 2585301, 1);
insert into Products (Name, Price, Status) values ('Tortillas - Flour, 8', 562156, 1);
insert into Products (Name, Price, Status) values ('Cheese - Swiss Sliced', 9167435, 0);
insert into Products (Name, Price, Status) values ('Juice - Lagoon Mango', 1949757, 1);
insert into Products (Name, Price, Status) values ('Ham - Cooked', 6441764, 1);
insert into Products (Name, Price, Status) values ('Oil - Sesame', 7717917, 1);
insert into Products (Name, Price, Status) values ('Tarragon - Fresh', 3411591, 1);
insert into Products (Name, Price, Status) values ('V8 Pet', 2536822, 0);
insert into Products (Name, Price, Status) values ('Shrimp, Dried, Small / Lb', 3669100, 0);
insert into Products (Name, Price, Status) values ('Wine - Niagara,vqa Reisling', 9971775, 1);
insert into Products (Name, Price, Status) values ('Nut - Almond, Blanched, Sliced', 9337951, 0);
insert into Products (Name, Price, Status) values ('Sauce - Gravy, Au Jus, Mix', 4693255, 1);
insert into Products (Name, Price, Status) values ('Pork Loin Bine - In Frenched', 9834666, 1);
insert into Products (Name, Price, Status) values ('Chinese Foods - Thick Noodles', 774010, 0);
insert into Products (Name, Price, Status) values ('Bar Special K', 577116, 1);
insert into Products (Name, Price, Status) values ('Grapes - Black', 506726, 0);
insert into Products (Name, Price, Status) values ('Wine - White, Gewurtzraminer', 6947568, 0);
insert into Products (Name, Price, Status) values ('Leeks - Baby, White', 7370176, 0);
insert into Products (Name, Price, Status) values ('Tea - Decaf Lipton', 680660, 0);
insert into Products (Name, Price, Status) values ('Bay Leaf', 4831123, 0);
insert into Products (Name, Price, Status) values ('Appetizer - Mushroom Tart', 6857685, 0);
insert into Products (Name, Price, Status) values ('Pepper - Yellow Bell', 9454055, 1);
insert into Products (Name, Price, Status) values ('Green Tea Refresher', 9246635, 1);
insert into Products (Name, Price, Status) values ('Hog / Sausage Casing - Pork', 4938252, 0);
insert into Products (Name, Price, Status) values ('Beer - Sleemans Cream Ale', 8391804, 1);
insert into Products (Name, Price, Status) values ('Mace', 2748235, 0);
insert into Products (Name, Price, Status) values ('Pork - European Side Bacon', 8620866, 1);
insert into Products (Name, Price, Status) values ('Wine - Muscadet Sur Lie', 2347463, 1);
insert into Products (Name, Price, Status) values ('Lemon Balm - Fresh', 9029049, 1);
insert into Products (Name, Price, Status) values ('Beef - Tenderloin - Aa', 7392473, 0);
insert into Products (Name, Price, Status) values ('Coffee Cup 8oz 5338cd', 4323030, 1);
insert into Products (Name, Price, Status) values ('Yucca', 220567, 0);
insert into Products (Name, Price, Status) values ('Apples - Sliced / Wedge', 7115400, 1);
insert into Products (Name, Price, Status) values ('Wine - Vidal Icewine Magnotta', 7090494, 0);
insert into Products (Name, Price, Status) values ('Cake - Dulce De Leche', 6081052, 1);
insert into Products (Name, Price, Status) values ('Brandy - Bar', 2356270, 0);
insert into Products (Name, Price, Status) values ('Basil - Seedlings Cookstown', 9887535, 0);
insert into Products (Name, Price, Status) values ('Soho Lychee Liqueur', 9416970, 0);
insert into Products (Name, Price, Status) values ('Ostrich - Fan Fillet', 417196, 1);
insert into Products (Name, Price, Status) values ('Wine - Bourgogne 2002, La', 838477, 0);
insert into Products (Name, Price, Status) values ('Pork - Loin, Bone - In', 3993191, 0);
insert into Products (Name, Price, Status) values ('Juice - Lime', 6207597, 1);
insert into Products (Name, Price, Status) values ('Beans - Soya Bean', 7272320, 0);
insert into Products (Name, Price, Status) values ('Nantucket - 518ml', 6305280, 1);
insert into Products (Name, Price, Status) values ('Wine - Vineland Estate Semi - Dry', 115966, 1);
insert into Products (Name, Price, Status) values ('Longos - Greek Salad', 6366515, 1);
insert into Products (Name, Price, Status) values ('Wine - Puligny Montrachet A.', 6033615, 1);
insert into Products (Name, Price, Status) values ('Prunes - Pitted', 6733452, 1);
insert into Products (Name, Price, Status) values ('Garlic - Peeled', 6474660, 1);
insert into Products (Name, Price, Status) values ('Cheese - Valancey', 4526368, 0);
insert into Products (Name, Price, Status) values ('Compound - Mocha', 7742041, 0);
insert into Products (Name, Price, Status) values ('Beef - Sushi Flat Iron Steak', 2872619, 1);
insert into Products (Name, Price, Status) values ('Steam Pan Full Lid', 6029144, 1);
insert into Products (Name, Price, Status) values ('Bread Fig And Almond', 3842420, 0);
insert into Products (Name, Price, Status) values ('Table Cloth 53x69 White', 9364990, 0);
insert into Products (Name, Price, Status) values ('Oysters - Smoked', 2614287, 1);
insert into Products (Name, Price, Status) values ('Tea - Herbal - 6 Asst', 6071475, 0);
insert into Products (Name, Price, Status) values ('Wine - Red, Pelee Island Merlot', 3622629, 0);
insert into Products (Name, Price, Status) values ('Pepper - Red Chili', 674972, 0);
insert into Products (Name, Price, Status) values ('Bread - White, Unsliced', 4603534, 0);
insert into Products (Name, Price, Status) values ('Tamarillo', 3938953, 1);
insert into Products (Name, Price, Status) values ('Shrimp - 31/40', 1740285, 0);
insert into Products (Name, Price, Status) values ('Potatoes - Purple, Organic', 1992546, 1);
insert into Products (Name, Price, Status) values ('Wine - Periguita Fonseca', 9807900, 1);
insert into Products (Name, Price, Status) values ('Ham - Proscuitto', 4986329, 0);
insert into Products (Name, Price, Status) values ('Beer - Upper Canada Lager', 5516775, 0);
insert into Products (Name, Price, Status) values ('Melon - Watermelon, Seedless', 4511212, 1);
insert into Products (Name, Price, Status) values ('Flower - Commercial Spider', 6447265, 1);
insert into Products (Name, Price, Status) values ('Lemonade - Island Tea, 591 Ml', 2760835, 1);
insert into Products (Name, Price, Status) values ('Pie Filling - Pumpkin', 4090414, 1);
insert into Products (Name, Price, Status) values ('Steel Wool', 6749787, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Treviso', 4008757, 1);
insert into Products (Name, Price, Status) values ('Wine - Rioja Campo Viejo', 7084877, 1);
insert into Products (Name, Price, Status) values ('Honey - Liquid', 6528163, 0);
insert into Products (Name, Price, Status) values ('Soup - Verve - Chipotle Chicken', 9625259, 0);
insert into Products (Name, Price, Status) values ('Tomatoes - Yellow Hot House', 4617020, 0);
insert into Products (Name, Price, Status) values ('Sauce - Caesar Dressing', 7548148, 1);
insert into Products (Name, Price, Status) values ('Coriander - Ground', 962115, 0);
insert into Products (Name, Price, Status) values ('Bread Base - Italian', 9237450, 0);
insert into Products (Name, Price, Status) values ('Nut - Almond, Blanched, Sliced', 6040150, 1);
insert into Products (Name, Price, Status) values ('Limes', 8195140, 0);
insert into Products (Name, Price, Status) values ('Bread Sour Rolls', 7414108, 1);
insert into Products (Name, Price, Status) values ('Alize Sunset', 5019907, 0);
insert into Products (Name, Price, Status) values ('Jam - Marmalade, Orange', 1551541, 1);
insert into Products (Name, Price, Status) values ('Juice - Apple, 500 Ml', 6788512, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Compound Coating', 2944893, 1);
insert into Products (Name, Price, Status) values ('Chicken - Wieners', 3164506, 0);
insert into Products (Name, Price, Status) values ('Croissant, Raw - Mini', 6271918, 0);
insert into Products (Name, Price, Status) values ('Wine - Trimbach Pinot Blanc', 7748060, 0);
insert into Products (Name, Price, Status) values ('Muffin Mix - Banana Nut', 2354056, 1);
insert into Products (Name, Price, Status) values ('Versatainer Nc - 9388', 1110750, 0);
insert into Products (Name, Price, Status) values ('Kiwi Gold Zespri', 3394818, 0);
insert into Products (Name, Price, Status) values ('Bag Stand', 5633147, 1);
insert into Products (Name, Price, Status) values ('Pastry - Choclate Baked', 5787388, 1);
insert into Products (Name, Price, Status) values ('Shrimp - 31/40', 9779951, 1);
insert into Products (Name, Price, Status) values ('Beer - Camerons Auburn', 7164446, 1);
insert into Products (Name, Price, Status) values ('Blueberries - Frozen', 7707645, 1);
insert into Products (Name, Price, Status) values ('Broom - Push', 6010908, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Arugula', 1137156, 0);
insert into Products (Name, Price, Status) values ('Oil - Shortening,liqud, Fry', 5252494, 0);
insert into Products (Name, Price, Status) values ('Wine - Cava Aria Estate Brut', 1189350, 0);
insert into Products (Name, Price, Status) values ('Kiwi Gold Zespri', 662766, 0);
insert into Products (Name, Price, Status) values ('Sun - Dried Tomatoes', 2384407, 1);
insert into Products (Name, Price, Status) values ('Breakfast Quesadillas', 6279296, 0);
insert into Products (Name, Price, Status) values ('Bread - Sour Sticks With Onion', 326817, 0);
insert into Products (Name, Price, Status) values ('Apple - Delicious, Red', 7344084, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Porcini Frozen', 7409533, 1);
insert into Products (Name, Price, Status) values ('Cheese - Manchego, Spanish', 4282898, 1);
insert into Products (Name, Price, Status) values ('Bread - Dark Rye', 8377142, 0);
insert into Products (Name, Price, Status) values ('Sauce - Chili', 1643033, 0);
insert into Products (Name, Price, Status) values ('Crackers Cheez It', 2538056, 1);
insert into Products (Name, Price, Status) values ('Cassis', 2165678, 0);
insert into Products (Name, Price, Status) values ('Lid - 3oz Med Rec', 3100956, 0);
insert into Products (Name, Price, Status) values ('Pants Custom Dry Clean', 4306176, 1);
insert into Products (Name, Price, Status) values ('Steampan - Foil', 728904, 1);
insert into Products (Name, Price, Status) values ('Pasta - Penne, Lisce, Dry', 1876433, 1);
insert into Products (Name, Price, Status) values ('Flower - Carnations', 5596502, 0);
insert into Products (Name, Price, Status) values ('Boogies', 8763915, 0);
insert into Products (Name, Price, Status) values ('Broom And Brush Rack Black', 2719195, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Lg - Cello', 3721477, 0);
insert into Products (Name, Price, Status) values ('Truffle Cups - Red', 8905656, 0);
insert into Products (Name, Price, Status) values ('Beef - Tongue, Fresh', 4516144, 0);
insert into Products (Name, Price, Status) values ('Wine - Domaine Boyar Royal', 6657034, 1);
insert into Products (Name, Price, Status) values ('Pork - Loin, Bone - In', 4465139, 1);
insert into Products (Name, Price, Status) values ('Muffin Batt - Ban Dream Zero', 4706703, 1);
insert into Products (Name, Price, Status) values ('Kiwano', 2270441, 1);
insert into Products (Name, Price, Status) values ('Oil - Safflower', 7254325, 0);
insert into Products (Name, Price, Status) values ('Island Oasis - Ice Cream Mix', 6335573, 0);
insert into Products (Name, Price, Status) values ('Wine - Vovray Sec Domaine Huet', 9869744, 0);
insert into Products (Name, Price, Status) values ('Pork - Back, Short Cut, Boneless', 1985479, 1);
insert into Products (Name, Price, Status) values ('Pears - Bosc', 7088603, 0);
insert into Products (Name, Price, Status) values ('Schnappes Peppermint - Walker', 8515099, 0);
insert into Products (Name, Price, Status) values ('Pepsi - Diet, 355 Ml', 2548022, 0);
insert into Products (Name, Price, Status) values ('Bread - Italian Corn Meal Poly', 7483436, 0);
insert into Products (Name, Price, Status) values ('Curry Powder', 1092472, 0);
insert into Products (Name, Price, Status) values ('Mustard Prepared', 3599074, 0);
insert into Products (Name, Price, Status) values ('Turnip - White', 2575425, 0);
insert into Products (Name, Price, Status) values ('Thermometer Digital', 7166415, 0);
insert into Products (Name, Price, Status) values ('Milk - Skim', 7611744, 0);
insert into Products (Name, Price, Status) values ('Bread Country Roll', 3562430, 1);
insert into Products (Name, Price, Status) values ('Chef Hat 25cm', 1312745, 0);
insert into Products (Name, Price, Status) values ('Longos - Penne With Pesto', 5430962, 1);
insert into Products (Name, Price, Status) values ('Gin - Gilbeys London, Dry', 6851521, 1);
insert into Products (Name, Price, Status) values ('Roe - White Fish', 7013589, 0);
insert into Products (Name, Price, Status) values ('Mussels - Cultivated', 6197744, 0);
insert into Products (Name, Price, Status) values ('Apple - Northern Spy', 6412579, 1);
insert into Products (Name, Price, Status) values ('Wine - Zonnebloem Pinotage', 7946762, 0);
insert into Products (Name, Price, Status) values ('Butter - Salted, Micro', 9483738, 1);
insert into Products (Name, Price, Status) values ('Wine - Magnotta - Bel Paese White', 9154418, 0);
insert into Products (Name, Price, Status) values ('Flax Seed', 8832395, 1);
insert into Products (Name, Price, Status) values ('Soup - French Onion, Dry', 8637511, 1);
insert into Products (Name, Price, Status) values ('Maple Syrup', 7488382, 0);
insert into Products (Name, Price, Status) values ('Muffin Hinge Container 6', 9383670, 1);
insert into Products (Name, Price, Status) values ('Nut - Pine Nuts, Whole', 3088515, 1);
insert into Products (Name, Price, Status) values ('Lobster - Canned Premium', 3951789, 0);
insert into Products (Name, Price, Status) values ('Beets - Candy Cane, Organic', 8460815, 1);
insert into Products (Name, Price, Status) values ('Vaccum Bag 10x13', 7628020, 0);
insert into Products (Name, Price, Status) values ('Ecolab - Hand Soap Form Antibac', 58161, 0);
insert into Products (Name, Price, Status) values ('Wine - Dubouef Macon - Villages', 7690313, 0);
insert into Products (Name, Price, Status) values ('Beef - Cooked, Corned', 6720000, 1);
insert into Products (Name, Price, Status) values ('Bread - Roll, Italian', 1635155, 0);
insert into Products (Name, Price, Status) values ('Crackers - Melba Toast', 6167232, 0);
insert into Products (Name, Price, Status) values ('Eggplant Italian', 900584, 0);
insert into Products (Name, Price, Status) values ('Muffin - Mix - Mango Sour Cherry', 8692579, 0);
insert into Products (Name, Price, Status) values ('Bread - Raisin', 439095, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Spring Mix', 3787098, 0);
insert into Products (Name, Price, Status) values ('Pear - Prickly', 8042564, 1);
insert into Products (Name, Price, Status) values ('Dragon Fruit', 7062954, 0);
insert into Products (Name, Price, Status) values ('Wine - Sawmill Creek Autumn', 3203116, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Portebello', 3606960, 0);
insert into Products (Name, Price, Status) values ('Apples - Sliced / Wedge', 4286004, 0);
insert into Products (Name, Price, Status) values ('Tomatoes - Heirloom', 2898304, 0);
insert into Products (Name, Price, Status) values ('Foam Cup 6 Oz', 6076932, 0);
insert into Products (Name, Price, Status) values ('Instant Coffee', 6025166, 1);
insert into Products (Name, Price, Status) values ('Evaporated Milk - Skim', 7757987, 1);
insert into Products (Name, Price, Status) values ('Madeira', 1441472, 1);
insert into Products (Name, Price, Status) values ('Wine - Hardys Bankside Shiraz', 420880, 0);
insert into Products (Name, Price, Status) values ('Nestea - Iced Tea', 8751099, 0);
insert into Products (Name, Price, Status) values ('Pasta - Lasagna Noodle, Frozen', 3746495, 0);
insert into Products (Name, Price, Status) values ('Miso Paste White', 2479848, 1);
insert into Products (Name, Price, Status) values ('Wine - Rubyport', 895688, 1);
insert into Products (Name, Price, Status) values ('Broom - Corn', 5329930, 0);
insert into Products (Name, Price, Status) values ('Tea - Orange Pekoe', 5141643, 1);
insert into Products (Name, Price, Status) values ('Ocean Spray - Kiwi Strawberry', 5036329, 0);
insert into Products (Name, Price, Status) values ('Tea - Herbal I Love Lemon', 5697815, 1);
insert into Products (Name, Price, Status) values ('Nectarines', 8261977, 0);
insert into Products (Name, Price, Status) values ('Rum - Dark, Bacardi, Black', 1832068, 1);
insert into Products (Name, Price, Status) values ('Cumin - Ground', 218609, 0);
insert into Products (Name, Price, Status) values ('English Muffin', 3210403, 1);
insert into Products (Name, Price, Status) values ('Wine - Sauvignon Blanc', 4093438, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Crimini', 269063, 1);
insert into Products (Name, Price, Status) values ('Tomatoes - Orange', 2298086, 1);
insert into Products (Name, Price, Status) values ('Muffin - Blueberry Individual', 6084312, 1);
insert into Products (Name, Price, Status) values ('Cheese - Swiss Sliced', 8424606, 1);
insert into Products (Name, Price, Status) values ('Sambuca - Ramazzotti', 9700143, 0);
insert into Products (Name, Price, Status) values ('Bag - Bread, White, Plain', 6010772, 1);
insert into Products (Name, Price, Status) values ('Wine - Rhine Riesling Wolf Blass', 8597951, 1);
insert into Products (Name, Price, Status) values ('Pork - Loin, Bone - In', 2345995, 0);
insert into Products (Name, Price, Status) values ('Cheese - Shred Cheddar / Mozza', 9023238, 1);
insert into Products (Name, Price, Status) values ('Petite Baguette', 9946314, 0);
insert into Products (Name, Price, Status) values ('Pate - Liver', 9912902, 1);
insert into Products (Name, Price, Status) values ('Sprouts - Bean', 4231952, 1);
insert into Products (Name, Price, Status) values ('Olives - Black, Pitted', 4084483, 1);
insert into Products (Name, Price, Status) values ('Cookies Almond Hazelnut', 6377140, 0);
insert into Products (Name, Price, Status) values ('Loaf Pan - 2 Lb, Foil', 8195773, 0);
insert into Products (Name, Price, Status) values ('Tray - 16in Rnd Blk', 8813680, 0);
insert into Products (Name, Price, Status) values ('Pepper - White, Ground', 4495109, 1);
insert into Products (Name, Price, Status) values ('Wine - Mondavi Coastal Private', 3736209, 0);
insert into Products (Name, Price, Status) values ('Cocoa Butter', 8654326, 1);
insert into Products (Name, Price, Status) values ('Cheese - Fontina', 6267725, 0);
insert into Products (Name, Price, Status) values ('Icecream - Dstk Strw Chseck', 1118670, 1);
insert into Products (Name, Price, Status) values ('Spinach - Packaged', 8946255, 1);
insert into Products (Name, Price, Status) values ('Coffee - Frthy Coffee Crisp', 6787647, 1);
insert into Products (Name, Price, Status) values ('Mushroom - Crimini', 5275059, 0);
insert into Products (Name, Price, Status) values ('Orange - Canned, Mandarin', 9147738, 0);
insert into Products (Name, Price, Status) values ('Wine - Chianti Classica Docg', 6817229, 0);
insert into Products (Name, Price, Status) values ('Teriyaki Sauce', 9707410, 1);
insert into Products (Name, Price, Status) values ('Bread - Roll, Soft White Round', 4099373, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Romaine', 4029189, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Belgian Endive', 4114823, 1);
insert into Products (Name, Price, Status) values ('Tendrils - Baby Pea, Organic', 4370018, 0);
insert into Products (Name, Price, Status) values ('Muffin Mix - Chocolate Chip', 635270, 1);
insert into Products (Name, Price, Status) values ('Tuna - Loin', 9494460, 0);
insert into Products (Name, Price, Status) values ('Milk - 2% 250 Ml', 983063, 0);
insert into Products (Name, Price, Status) values ('Spinach - Packaged', 1901247, 1);
insert into Products (Name, Price, Status) values ('Bread - Roll, Italian', 5875211, 1);
insert into Products (Name, Price, Status) values ('White Fish - Filets', 7554918, 1);
insert into Products (Name, Price, Status) values ('Turkey - Breast, Boneless Sk On', 8592722, 0);
insert into Products (Name, Price, Status) values ('Cabbage - Savoy', 5483334, 0);
insert into Products (Name, Price, Status) values ('Guava', 4014263, 0);
insert into Products (Name, Price, Status) values ('Lamb - Whole Head Off,nz', 9396073, 0);
insert into Products (Name, Price, Status) values ('Brandy - Orange, Mc Guiness', 7090309, 1);
insert into Products (Name, Price, Status) values ('Vinegar - Balsamic, White', 8627580, 1);
insert into Products (Name, Price, Status) values ('Macaroons - Homestyle Two Bit', 2955653, 1);
insert into Products (Name, Price, Status) values ('Capon - Breast, Double, Wing On', 9897547, 0);
insert into Products (Name, Price, Status) values ('Soup - Cream Of Broccoli', 793927, 1);
insert into Products (Name, Price, Status) values ('Cake - Cake Sheet Macaroon', 1933586, 1);
insert into Products (Name, Price, Status) values ('Gooseberry', 791327, 0);
insert into Products (Name, Price, Status) values ('Soup Campbells - Italian Wedding', 7076966, 1);
insert into Products (Name, Price, Status) values ('Cookie Double Choco', 4254359, 0);
insert into Products (Name, Price, Status) values ('Thermometer Digital', 6379071, 0);
insert into Products (Name, Price, Status) values ('Soup - Knorr, Veg / Beef', 1330449, 1);
insert into Products (Name, Price, Status) values ('Cookie - Dough Variety', 4863369, 1);
insert into Products (Name, Price, Status) values ('Sugar - White Packet', 8460427, 1);
insert into Products (Name, Price, Status) values ('Quail - Whole, Bone - In', 232237, 0);
insert into Products (Name, Price, Status) values ('Liquid Aminios Acid - Braggs', 5212963, 1);
insert into Products (Name, Price, Status) values ('Instant Coffee', 9200825, 1);
insert into Products (Name, Price, Status) values ('Veal - Sweetbread', 5936385, 0);
insert into Products (Name, Price, Status) values ('Nantucket - Orange Mango Cktl', 4292734, 1);
insert into Products (Name, Price, Status) values ('Pasta - Orzo, Dry', 9356073, 0);
insert into Products (Name, Price, Status) values ('Wine - Vovray Sec Domaine Huet', 2729780, 1);
insert into Products (Name, Price, Status) values ('Muffin - Carrot Individual Wrap', 6947278, 1);
insert into Products (Name, Price, Status) values ('Irish Cream - Butterscotch', 9276781, 1);
insert into Products (Name, Price, Status) values ('Coffee Cup 8oz 5338cd', 9295828, 1);
insert into Products (Name, Price, Status) values ('Chinese Foods - Chicken', 7745285, 1);
insert into Products (Name, Price, Status) values ('Tea - Grapefruit Green Tea', 2468272, 1);
insert into Products (Name, Price, Status) values ('Cleaner - Comet', 8283138, 0);
insert into Products (Name, Price, Status) values ('Puree - Guava', 3667882, 1);
insert into Products (Name, Price, Status) values ('Onions - Pearl', 6795877, 1);
insert into Products (Name, Price, Status) values ('Tart Shells - Savory, 4', 842482, 1);
insert into Products (Name, Price, Status) values ('Maintenance Removal Charge', 4153741, 0);
insert into Products (Name, Price, Status) values ('Oil - Hazelnut', 2895454, 1);
insert into Products (Name, Price, Status) values ('Flour - Masa De Harina Mexican', 7319266, 1);
insert into Products (Name, Price, Status) values ('Creme De Cacao Mcguines', 9374306, 0);
insert into Products (Name, Price, Status) values ('Strawberries', 169308, 1);
insert into Products (Name, Price, Status) values ('Nestea - Iced Tea', 7108711, 1);
insert into Products (Name, Price, Status) values ('Cafe Royale', 1501619, 1);
insert into Products (Name, Price, Status) values ('Tea - Vanilla Chai', 3392577, 1);
insert into Products (Name, Price, Status) values ('Beer - Blue', 201226, 0);
insert into Products (Name, Price, Status) values ('Napkin - Dinner, White', 9210491, 1);
insert into Products (Name, Price, Status) values ('Latex Rubber Gloves Size 9', 2549799, 0);
insert into Products (Name, Price, Status) values ('Cheese - Havarti, Salsa', 5841061, 1);
insert into Products (Name, Price, Status) values ('Bowl 12 Oz - Showcase 92012', 3006016, 0);
insert into Products (Name, Price, Status) values ('Chicken - Wings, Tip Off', 743498, 0);
insert into Products (Name, Price, Status) values ('Skewers - Bamboo', 8062453, 0);
insert into Products (Name, Price, Status) values ('Food Colouring - Red', 935908, 0);
insert into Products (Name, Price, Status) values ('Turnip - White', 5158353, 1);
insert into Products (Name, Price, Status) values ('Turkey - Oven Roast Breast', 8181160, 1);
insert into Products (Name, Price, Status) values ('Pate Pans Yellow', 8372928, 0);
insert into Products (Name, Price, Status) values ('Juice - Lemon', 9370345, 0);
insert into Products (Name, Price, Status) values ('Cake - Box Window 10x10x2.5', 8785116, 0);
insert into Products (Name, Price, Status) values ('Pasta - Ravioli', 3743199, 0);
insert into Products (Name, Price, Status) values ('Horseradish - Prepared', 632429, 1);
insert into Products (Name, Price, Status) values ('Wine - Savigny - Les - Beaune', 6794820, 1);
insert into Products (Name, Price, Status) values ('Muffin Batt - Carrot Spice', 8581112, 0);
insert into Products (Name, Price, Status) values ('Nantuket Peach Orange', 387926, 1);
insert into Products (Name, Price, Status) values ('Nut - Pecan, Halves', 3720112, 0);
insert into Products (Name, Price, Status) values ('Lid - High Heat, Super Clear', 7838659, 1);
insert into Products (Name, Price, Status) values ('Petite Baguette', 4515027, 1);
insert into Products (Name, Price, Status) values ('Split Peas - Green, Dry', 3782402, 0);
insert into Products (Name, Price, Status) values ('Lamb - Racks, Frenched', 9434549, 1);
insert into Products (Name, Price, Status) values ('Veal - Inside, Choice', 5361998, 0);
insert into Products (Name, Price, Status) values ('Coffee - Decaffeinato Coffee', 454345, 1);
insert into Products (Name, Price, Status) values ('Calypso - Lemonade', 5918247, 1);
insert into Products (Name, Price, Status) values ('Hog / Sausage Casing - Pork', 2977948, 1);
insert into Products (Name, Price, Status) values ('Vegetable - Base', 7656666, 0);
insert into Products (Name, Price, Status) values ('Oil - Pumpkinseed', 7868480, 1);
insert into Products (Name, Price, Status) values ('Lid Tray - 12in Dome', 1856064, 1);
insert into Products (Name, Price, Status) values ('Dooleys Toffee', 6887798, 0);
insert into Products (Name, Price, Status) values ('Toothpick Frilled', 7935123, 0);
insert into Products (Name, Price, Status) values ('Maintenance Removal Charge', 8970552, 0);
insert into Products (Name, Price, Status) values ('Pancetta', 6365917, 0);
insert into Products (Name, Price, Status) values ('Table Cloth 54x72 White', 7108724, 1);
insert into Products (Name, Price, Status) values ('Veal - Ground', 7807934, 1);
insert into Products (Name, Price, Status) values ('Cheese - Shred Cheddar / Mozza', 1202529, 1);
insert into Products (Name, Price, Status) values ('Mushroom - Crimini', 9322011, 0);
insert into Products (Name, Price, Status) values ('Dc - Frozen Momji', 6199737, 0);
insert into Products (Name, Price, Status) values ('Lemon Tarts', 9765064, 1);
insert into Products (Name, Price, Status) values ('Ice Cream - Strawberry', 3623818, 0);
insert into Products (Name, Price, Status) values ('Muffin - Mix - Creme Brule 15l', 8309007, 1);
insert into Products (Name, Price, Status) values ('Shopper Bag - S - 4', 2339298, 1);
insert into Products (Name, Price, Status) values ('Pastry - Banana Muffin - Mini', 9181920, 1);
insert into Products (Name, Price, Status) values ('Raspberries - Frozen', 2816300, 0);
insert into Products (Name, Price, Status) values ('Garlic', 8984686, 0);
insert into Products (Name, Price, Status) values ('French Pastries', 3969313, 1);
insert into Products (Name, Price, Status) values ('Sprouts - Bean', 4655704, 1);
insert into Products (Name, Price, Status) values ('Appetiser - Bought', 9052134, 1);
insert into Products (Name, Price, Status) values ('Wine - Prosecco Valdobiaddene', 8799655, 1);
insert into Products (Name, Price, Status) values ('Wine - Merlot Vina Carmen', 3915508, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Curly Endive', 7742540, 1);
insert into Products (Name, Price, Status) values ('Pepper - Chili Powder', 8756388, 0);
insert into Products (Name, Price, Status) values ('Banana Turning', 3069579, 0);
insert into Products (Name, Price, Status) values ('Aspic - Light', 930432, 0);
insert into Products (Name, Price, Status) values ('Beef - Prime Rib Aaa', 9012677, 1);
insert into Products (Name, Price, Status) values ('Container - Clear 16 Oz', 8897537, 1);
insert into Products (Name, Price, Status) values ('Pate Pans Yellow', 4709348, 0);
insert into Products (Name, Price, Status) values ('Ham - Proscuitto', 6480190, 0);
insert into Products (Name, Price, Status) values ('Bread - Raisin', 8857094, 0);
insert into Products (Name, Price, Status) values ('Red Cod Fillets - 225g', 386963, 1);
insert into Products (Name, Price, Status) values ('Sparkling Wine - Rose, Freixenet', 9634983, 1);
insert into Products (Name, Price, Status) values ('Wine - Zinfandel Rosenblum', 7311548, 0);
insert into Products (Name, Price, Status) values ('Pie Filling - Apple', 9139106, 0);
insert into Products (Name, Price, Status) values ('Laundry - Bag Cloth', 7902749, 1);
insert into Products (Name, Price, Status) values ('Creme De Cacao White', 8965177, 1);
insert into Products (Name, Price, Status) values ('Wine - Manischewitz Concord', 4319696, 0);
insert into Products (Name, Price, Status) values ('Oil - Grapeseed Oil', 4237343, 0);
insert into Products (Name, Price, Status) values ('Fish - Soup Base, Bouillon', 8969787, 1);
insert into Products (Name, Price, Status) values ('Chips - Potato Jalapeno', 7046469, 1);
insert into Products (Name, Price, Status) values ('Cheese - Feta', 493651, 0);
insert into Products (Name, Price, Status) values ('Urban Zen Drinks', 6754761, 0);
insert into Products (Name, Price, Status) values ('Bagel - Plain', 7575977, 0);
insert into Products (Name, Price, Status) values ('Red Snapper - Fresh, Whole', 5431327, 1);
insert into Products (Name, Price, Status) values ('Cookies Cereal Nut', 4410033, 1);
insert into Products (Name, Price, Status) values ('Soup - Campbells, Cream Of', 5162413, 0);
insert into Products (Name, Price, Status) values ('Wine - Saint - Bris 2002, Sauv', 1764668, 0);
insert into Products (Name, Price, Status) values ('Buffalo - Short Rib Fresh', 8255945, 1);
insert into Products (Name, Price, Status) values ('Onions - Pearl', 527979, 1);
insert into Products (Name, Price, Status) values ('Sausage - Meat', 8104567, 1);
insert into Products (Name, Price, Status) values ('Strawberries', 6262365, 0);
insert into Products (Name, Price, Status) values ('Turnip - White', 4225834, 1);
insert into Products (Name, Price, Status) values ('Beets', 9954409, 1);
insert into Products (Name, Price, Status) values ('Venison - Ground', 4629411, 1);
insert into Products (Name, Price, Status) values ('Soup Campbells Mexicali Tortilla', 7247923, 1);
insert into Products (Name, Price, Status) values ('Sugar - Crumb', 1232759, 1);
insert into Products (Name, Price, Status) values ('Oil - Olive, Extra Virgin', 8216620, 1);
insert into Products (Name, Price, Status) values ('Energy Drink - Redbull 355ml', 8265753, 0);
insert into Products (Name, Price, Status) values ('Coffee - Decaffeinato Coffee', 7189996, 0);
insert into Products (Name, Price, Status) values ('Sauce - Thousand Island', 8343484, 1);
insert into Products (Name, Price, Status) values ('Beef - Tenderlion, Center Cut', 8806989, 0);
insert into Products (Name, Price, Status) values ('Steampan - Lid For Half Size', 6271677, 0);
insert into Products (Name, Price, Status) values ('Tomatoes - Yellow Hot House', 2537826, 0);
insert into Products (Name, Price, Status) values ('Brocolinni - Gaylan, Chinese', 6073983, 0);
insert into Products (Name, Price, Status) values ('Island Oasis - Cappucino Mix', 6050121, 1);
insert into Products (Name, Price, Status) values ('Beans - Turtle, Black, Dry', 9311031, 0);
insert into Products (Name, Price, Status) values ('Flower - Commercial Bronze', 5063391, 0);
insert into Products (Name, Price, Status) values ('Spinach - Baby', 2452035, 0);
insert into Products (Name, Price, Status) values ('Kirsch - Schloss', 20431, 1);
insert into Products (Name, Price, Status) values ('Pasta - Detalini, White, Fresh', 7110664, 1);
insert into Products (Name, Price, Status) values ('Juice - Lagoon Mango', 5764545, 0);
insert into Products (Name, Price, Status) values ('Cup - 8oz Coffee Perforated', 730555, 1);
insert into Products (Name, Price, Status) values ('Roe - Flying Fish', 7293724, 1);
insert into Products (Name, Price, Status) values ('Sugar - Cubes', 4348878, 0);
insert into Products (Name, Price, Status) values ('Lamb - Racks, Frenched', 7780018, 0);
insert into Products (Name, Price, Status) values ('Soup V8 Roasted Red Pepper', 3833268, 0);
insert into Products (Name, Price, Status) values ('Burger Veggie', 9922324, 0);
insert into Products (Name, Price, Status) values ('Beef Cheek Fresh', 1804839, 0);
insert into Products (Name, Price, Status) values ('Beans - Fava Fresh', 6731230, 1);
insert into Products (Name, Price, Status) values ('Bread Crumbs - Japanese Style', 7124027, 1);
insert into Products (Name, Price, Status) values ('Spic And Span All Purpose', 8085045, 1);
insert into Products (Name, Price, Status) values ('Cheese - Mozzarella', 8337971, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Spring Mix', 5843302, 0);
insert into Products (Name, Price, Status) values ('Oil - Macadamia', 5782561, 0);
insert into Products (Name, Price, Status) values ('Pancetta', 6980308, 0);
insert into Products (Name, Price, Status) values ('Tarts Assorted', 2164277, 1);
insert into Products (Name, Price, Status) values ('Banana', 648100, 0);
insert into Products (Name, Price, Status) values ('Wine - Vovray Sec Domaine Huet', 7306552, 0);
insert into Products (Name, Price, Status) values ('Mushroom - Chanterelle Frozen', 2992381, 0);
insert into Products (Name, Price, Status) values ('Veal - Nuckle', 9533304, 1);
insert into Products (Name, Price, Status) values ('Cranberries - Frozen', 9455646, 0);
insert into Products (Name, Price, Status) values ('Chocolate - Compound Coating', 5784498, 1);
insert into Products (Name, Price, Status) values ('Paper Towel Touchless', 3408177, 0);
insert into Products (Name, Price, Status) values ('Island Oasis - Banana Daiquiri', 25397, 1);
insert into Products (Name, Price, Status) values ('Cheese - Gouda', 3960830, 1);
insert into Products (Name, Price, Status) values ('Wasabi Paste', 5912827, 0);
insert into Products (Name, Price, Status) values ('Anchovy Fillets', 7505708, 1);
insert into Products (Name, Price, Status) values ('Wine - Magnotta - Bel Paese White', 2225006, 1);
insert into Products (Name, Price, Status) values ('Mustard - Pommery', 6994138, 1);
insert into Products (Name, Price, Status) values ('Bar Mix - Lemon', 4501004, 1);
insert into Products (Name, Price, Status) values ('Cherries - Bing, Canned', 8809660, 0);
insert into Products (Name, Price, Status) values ('Flounder - Fresh', 4694753, 0);
insert into Products (Name, Price, Status) values ('Crush - Cream Soda', 5907429, 0);
insert into Products (Name, Price, Status) values ('Cheese - Comte', 4147027, 1);
insert into Products (Name, Price, Status) values ('Beer - Camerons Auburn', 6737921, 0);
insert into Products (Name, Price, Status) values ('Pepper - Sorrano', 4650013, 1);
insert into Products (Name, Price, Status) values ('Wine - Cava Aria Estate Brut', 9984235, 1);
insert into Products (Name, Price, Status) values ('Cheese - Havarti, Roasted Garlic', 1976562, 1);
insert into Products (Name, Price, Status) values ('Dill Weed - Fresh', 9530117, 1);
insert into Products (Name, Price, Status) values ('Sweet Pea Sprouts', 7221671, 1);
insert into Products (Name, Price, Status) values ('7up Diet, 355 Ml', 7061869, 0);
insert into Products (Name, Price, Status) values ('Coffee - Decaffeinato Coffee', 7439530, 0);
insert into Products (Name, Price, Status) values ('Pastry - Banana Tea Loaf', 1068325, 0);
insert into Products (Name, Price, Status) values ('Ginsing - Fresh', 5382891, 0);
insert into Products (Name, Price, Status) values ('Pails With Lids', 7236671, 0);
insert into Products (Name, Price, Status) values ('Cheese - Sheep Milk', 7383162, 0);
insert into Products (Name, Price, Status) values ('Beef - Kobe Striploin', 7540609, 0);
insert into Products (Name, Price, Status) values ('Wine - Gewurztraminer Pierre', 6610585, 0);
insert into Products (Name, Price, Status) values ('Skewers - Bamboo', 2173093, 1);
insert into Products (Name, Price, Status) values ('Muffin - Mix - Bran And Maple 15l', 5987576, 0);
insert into Products (Name, Price, Status) values ('Wine - Acient Coast Caberne', 5256291, 1);
insert into Products (Name, Price, Status) values ('Coffee - Egg Nog Capuccino', 8851971, 0);
insert into Products (Name, Price, Status) values ('Boogies', 4651928, 1);
insert into Products (Name, Price, Status) values ('Gelatine Powder', 6103404, 1);
insert into Products (Name, Price, Status) values ('Pork - Hock And Feet Attached', 8196420, 0);
insert into Products (Name, Price, Status) values ('Liners - Banana, Paper', 7620586, 1);
insert into Products (Name, Price, Status) values ('Salt - Celery', 5608675, 1);
insert into Products (Name, Price, Status) values ('Buffalo - Short Rib Fresh', 6665323, 1);
insert into Products (Name, Price, Status) values ('Wine - Black Tower Qr', 7205425, 1);
insert into Products (Name, Price, Status) values ('Eel - Smoked', 8924735, 0);
insert into Products (Name, Price, Status) values ('Truffle Shells - White Chocolate', 8270696, 1);
insert into Products (Name, Price, Status) values ('Blueberries - Frozen', 7048693, 1);
insert into Products (Name, Price, Status) values ('Mushroom - Enoki, Dry', 1452320, 0);
insert into Products (Name, Price, Status) values ('Cake - Dulce De Leche', 3777007, 0);
insert into Products (Name, Price, Status) values ('Pastry - Chocolate Chip Muffin', 6952624, 1);
insert into Products (Name, Price, Status) values ('Island Oasis - Pina Colada', 2374009, 1);
insert into Products (Name, Price, Status) values ('Beets - Mini Golden', 5759581, 0);
insert into Products (Name, Price, Status) values ('Mustard - Dry, Powder', 275304, 0);
insert into Products (Name, Price, Status) values ('Creamers - 10%', 7566517, 1);
insert into Products (Name, Price, Status) values ('Foam Dinner Plate', 579167, 0);
insert into Products (Name, Price, Status) values ('Pepsi, 355 Ml', 587377, 0);
insert into Products (Name, Price, Status) values ('Clams - Canned', 1766652, 0);
insert into Products (Name, Price, Status) values ('Bread - Raisin', 5495338, 1);
insert into Products (Name, Price, Status) values ('Sauce - Gravy, Au Jus, Mix', 6673033, 0);
insert into Products (Name, Price, Status) values ('Food Colouring - Green', 3664297, 1);
insert into Products (Name, Price, Status) values ('Cake - Cake Sheet Macaroon', 31253, 1);
insert into Products (Name, Price, Status) values ('Apricots Fresh', 2428893, 1);
insert into Products (Name, Price, Status) values ('Roe - Lump Fish, Red', 2226569, 1);
insert into Products (Name, Price, Status) values ('Crab - Meat', 5409455, 1);
insert into Products (Name, Price, Status) values ('Juice - Ocean Spray Cranberry', 3608201, 0);
insert into Products (Name, Price, Status) values ('Oil - Peanut', 1479536, 0);
insert into Products (Name, Price, Status) values ('Soup Campbells - Tomato Bisque', 5964141, 1);
insert into Products (Name, Price, Status) values ('Shrimp - Black Tiger 16/20', 6103803, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Arugula', 5155258, 1);
insert into Products (Name, Price, Status) values ('Flower - Commercial Spider', 4860423, 0);
insert into Products (Name, Price, Status) values ('Muffin - Mix - Strawberry Rhubarb', 5830879, 1);
insert into Products (Name, Price, Status) values ('Bandage - Flexible Neon', 8823199, 1);
insert into Products (Name, Price, Status) values ('Beer - Creemore', 6104484, 1);
insert into Products (Name, Price, Status) values ('Pickles - Gherkins', 8910137, 0);
insert into Products (Name, Price, Status) values ('Pesto - Primerba, Paste', 3291470, 1);
insert into Products (Name, Price, Status) values ('Chocolate - Compound Coating', 9397630, 1);
insert into Products (Name, Price, Status) values ('Pastry - Cheese Baked Scones', 9471791, 1);
insert into Products (Name, Price, Status) values ('Sproutsmustard Cress', 5315600, 0);
insert into Products (Name, Price, Status) values ('Pasta - Ravioli', 5284459, 1);
insert into Products (Name, Price, Status) values ('Dried Peach', 7131895, 0);
insert into Products (Name, Price, Status) values ('Trout - Rainbow, Frozen', 7229005, 0);
insert into Products (Name, Price, Status) values ('Garlic Powder', 5816503, 0);
insert into Products (Name, Price, Status) values ('Marjoram - Fresh', 8993703, 0);
insert into Products (Name, Price, Status) values ('Artichokes - Jerusalem', 427155, 0);
insert into Products (Name, Price, Status) values ('Cheese - Perron Cheddar', 7359880, 1);
insert into Products (Name, Price, Status) values ('Oneshot Automatic Soap System', 1448427, 0);
insert into Products (Name, Price, Status) values ('Cream - 35%', 7415327, 1);
insert into Products (Name, Price, Status) values ('Radish', 1825292, 1);
insert into Products (Name, Price, Status) values ('Tomato - Plum With Basil', 2919756, 0);
insert into Products (Name, Price, Status) values ('Tomatoes - Heirloom', 9340417, 1);
insert into Products (Name, Price, Status) values ('Asparagus - White, Canned', 182327, 0);
insert into Products (Name, Price, Status) values ('Smoked Paprika', 1907777, 0);
insert into Products (Name, Price, Status) values ('Bread - Multigrain Oval', 4390453, 0);
insert into Products (Name, Price, Status) values ('Bread - Calabrese Baguette', 6725176, 0);
insert into Products (Name, Price, Status) values ('Syrup - Chocolate', 1246476, 1);
insert into Products (Name, Price, Status) values ('Veal Inside - Provimi', 3924524, 1);
insert into Products (Name, Price, Status) values ('Beets - Pickled', 2794461, 0);
insert into Products (Name, Price, Status) values ('Extract - Vanilla,artificial', 3187420, 1);
insert into Products (Name, Price, Status) values ('Poppy Seed', 1581482, 0);
insert into Products (Name, Price, Status) values ('Salmon - Sockeye Raw', 4288224, 0);
insert into Products (Name, Price, Status) values ('Pastry - Plain Baked Croissant', 1286966, 1);
insert into Products (Name, Price, Status) values ('Nut - Pistachio, Shelled', 5743179, 0);
insert into Products (Name, Price, Status) values ('Fudge - Chocolate Fudge', 3908585, 1);
insert into Products (Name, Price, Status) values ('Tuna - Canned, Flaked, Light', 5256338, 0);
insert into Products (Name, Price, Status) values ('Vinegar - Balsamic, White', 1576144, 0);
insert into Products (Name, Price, Status) values ('Gingerale - Diet - Schweppes', 6696587, 1);
insert into Products (Name, Price, Status) values ('Pasta - Penne Primavera, Single', 6017299, 0);
insert into Products (Name, Price, Status) values ('Flour - Teff', 4677741, 1);
insert into Products (Name, Price, Status) values ('Cabbage - Red', 5087011, 1);
insert into Products (Name, Price, Status) values ('French Pastries', 164458, 1);
insert into Products (Name, Price, Status) values ('Bar Energy Chocchip', 1228445, 1);
insert into Products (Name, Price, Status) values ('Assorted Desserts', 7993212, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Sea / Sea Asparagus', 9538163, 1);
insert into Products (Name, Price, Status) values ('Onion - Dried', 4355016, 0);
insert into Products (Name, Price, Status) values ('Cookies - Amaretto', 6066359, 1);
insert into Products (Name, Price, Status) values ('Numi - Assorted Teas', 2752687, 0);
insert into Products (Name, Price, Status) values ('Dried Peach', 1171761, 1);
insert into Products (Name, Price, Status) values ('Cookie Dough - Chocolate Chip', 7703038, 1);
insert into Products (Name, Price, Status) values ('Capon - Breast, Double, Wing On', 8872078, 1);
insert into Products (Name, Price, Status) values ('Chutney Sauce - Mango', 1486662, 0);
insert into Products (Name, Price, Status) values ('Bread Crumbs - Japanese Style', 7490355, 1);
insert into Products (Name, Price, Status) values ('Wine - Red, Cabernet Sauvignon', 3900525, 0);
insert into Products (Name, Price, Status) values ('Veal - Liver', 9062293, 0);
insert into Products (Name, Price, Status) values ('The Pop Shoppe - Lime Rickey', 4041960, 0);
insert into Products (Name, Price, Status) values ('Parsley Italian - Fresh', 7791807, 1);
insert into Products (Name, Price, Status) values ('Corn - Mini', 3691076, 1);
insert into Products (Name, Price, Status) values ('Noodles - Cellophane, Thin', 327523, 0);
insert into Products (Name, Price, Status) values ('Pepsi - 600ml', 738530, 0);
insert into Products (Name, Price, Status) values ('Emulsifier', 2579500, 1);
insert into Products (Name, Price, Status) values ('Milk - Chocolate 250 Ml', 9445101, 1);
insert into Products (Name, Price, Status) values ('Wine - Mas Chicet Rose, Vintage', 9226312, 1);
insert into Products (Name, Price, Status) values ('Beer - Guiness', 5114331, 0);
insert into Products (Name, Price, Status) values ('Pasta - Cannelloni, Sheets, Fresh', 1443967, 1);
insert into Products (Name, Price, Status) values ('Table Cloth 120 Round White', 3158326, 1);
insert into Products (Name, Price, Status) values ('Cheese - Valancey', 467850, 1);
insert into Products (Name, Price, Status) values ('Wine - Red, Cabernet Merlot', 4831357, 0);
insert into Products (Name, Price, Status) values ('Jam - Raspberry,jar', 241747, 1);
insert into Products (Name, Price, Status) values ('Juice - Orangina', 7543569, 0);
insert into Products (Name, Price, Status) values ('Flower - Commercial Spider', 3426940, 0);
insert into Products (Name, Price, Status) values ('Beer - True North Strong Ale', 7592435, 0);
insert into Products (Name, Price, Status) values ('Wine - White, Cooking', 3220211, 1);
insert into Products (Name, Price, Status) values ('Oil - Olive', 6028648, 1);
insert into Products (Name, Price, Status) values ('Salt - Rock, Course', 6569333, 1);
insert into Products (Name, Price, Status) values ('Dooleys Toffee', 4590537, 1);
insert into Products (Name, Price, Status) values ('Bread Foccacia Whole', 5975314, 0);
insert into Products (Name, Price, Status) values ('Coriander - Ground', 3573745, 1);
insert into Products (Name, Price, Status) values ('Chicken - Soup Base', 5484021, 1);
insert into Products (Name, Price, Status) values ('Creme De Banane - Marie', 2572511, 0);
insert into Products (Name, Price, Status) values ('Nantucket - 518ml', 9963091, 0);
insert into Products (Name, Price, Status) values ('Stainless Steel Cleaner Vision', 4208050, 0);
insert into Products (Name, Price, Status) values ('Wakami Seaweed', 6468001, 0);
insert into Products (Name, Price, Status) values ('Appetizer - Southwestern', 4781239, 0);
insert into Products (Name, Price, Status) values ('Rice - Brown', 5109001, 0);
insert into Products (Name, Price, Status) values ('Rambutan', 8229953, 1);
insert into Products (Name, Price, Status) values ('Flour - Chickpea', 4450673, 1);
insert into Products (Name, Price, Status) values ('Bag Stand', 6297484, 0);
insert into Products (Name, Price, Status) values ('Shrimp - Black Tiger 6 - 8', 8414780, 1);
insert into Products (Name, Price, Status) values ('Island Oasis - Strawberry', 5690848, 1);
insert into Products (Name, Price, Status) values ('Bread - Roll, Calabrese', 8474259, 0);
insert into Products (Name, Price, Status) values ('Cookie Dough - Peanut Butter', 7135258, 0);
insert into Products (Name, Price, Status) values ('Gherkin', 8979600, 0);
insert into Products (Name, Price, Status) values ('Pomello', 5304788, 0);
insert into Products (Name, Price, Status) values ('Spinach - Spinach Leaf', 7442952, 1);
insert into Products (Name, Price, Status) values ('Beef - Tongue, Cooked', 9537582, 1);
insert into Products (Name, Price, Status) values ('Pastry - Choclate Baked', 130188, 0);
insert into Products (Name, Price, Status) values ('Yucca', 7028518, 0);
insert into Products (Name, Price, Status) values ('Chicken - Soup Base', 6955978, 1);
insert into Products (Name, Price, Status) values ('Juice - Orangina', 3118153, 1);
insert into Products (Name, Price, Status) values ('Cardamon Seed / Pod', 6857006, 0);
insert into Products (Name, Price, Status) values ('Worcestershire Sauce', 1751095, 1);
insert into Products (Name, Price, Status) values ('Jam - Raspberry', 8229896, 1);
insert into Products (Name, Price, Status) values ('Dc Hikiage Hira Huba', 5968706, 1);
insert into Products (Name, Price, Status) values ('Beef - Texas Style Burger', 73750, 0);
insert into Products (Name, Price, Status) values ('Quinoa', 7267088, 1);
insert into Products (Name, Price, Status) values ('Appetizer - Mini Egg Roll, Shrimp', 9695169, 0);
insert into Products (Name, Price, Status) values ('Coconut Milk - Unsweetened', 5101011, 1);
insert into Products (Name, Price, Status) values ('Sugar - Icing', 5948600, 0);
insert into Products (Name, Price, Status) values ('Fudge - Chocolate Fudge', 5087867, 0);
insert into Products (Name, Price, Status) values ('Sauce - Chili', 9367733, 0);
insert into Products (Name, Price, Status) values ('Dikon', 1791314, 1);
insert into Products (Name, Price, Status) values ('Brandy - Orange, Mc Guiness', 2881153, 1);
insert into Products (Name, Price, Status) values ('Pastry - Cheese Baked Scones', 8900886, 0);
insert into Products (Name, Price, Status) values ('Foil - Round Foil', 5231128, 1);
insert into Products (Name, Price, Status) values ('Pasta - Orecchiette', 5740629, 1);
insert into Products (Name, Price, Status) values ('Lemonade - Island Tea, 591 Ml', 3554665, 1);
insert into Products (Name, Price, Status) values ('Tilapia - Fillets', 2542692, 1);
insert into Products (Name, Price, Status) values ('Juice - Tomato, 10 Oz', 9064129, 0);
insert into Products (Name, Price, Status) values ('Carrots - Mini Red Organic', 1535464, 1);
insert into Products (Name, Price, Status) values ('Mushroom - White Button', 6503106, 1);
insert into Products (Name, Price, Status) values ('Fish - Halibut, Cold Smoked', 6216329, 1);
insert into Products (Name, Price, Status) values ('Wine - Red, Concha Y Toro', 8719914, 0);
insert into Products (Name, Price, Status) values ('Beer - Upper Canada Light', 7283038, 1);
insert into Products (Name, Price, Status) values ('Wine - Barbera Alba Doc 2001', 1902759, 1);
insert into Products (Name, Price, Status) values ('Turnip - Mini', 1635740, 0);
insert into Products (Name, Price, Status) values ('Bar Nature Valley', 4730046, 0);
insert into Products (Name, Price, Status) values ('Mustard - Seed', 9152224, 1);
insert into Products (Name, Price, Status) values ('Wine - Mas Chicet Rose, Vintage', 7128464, 0);
insert into Products (Name, Price, Status) values ('Wine - Harrow Estates, Vidal', 3187474, 0);
insert into Products (Name, Price, Status) values ('Sansho Powder', 2582490, 0);
insert into Products (Name, Price, Status) values ('Smoked Tongue', 4376300, 1);
insert into Products (Name, Price, Status) values ('Beef - Cow Feet Split', 2805772, 0);
insert into Products (Name, Price, Status) values ('Onion - Dried', 2535505, 0);
insert into Products (Name, Price, Status) values ('Napkin - Dinner, White', 2179557, 1);
insert into Products (Name, Price, Status) values ('Juice - Apple, 500 Ml', 8441237, 1);
insert into Products (Name, Price, Status) values ('Salmon - Fillets', 8604442, 0);
insert into Products (Name, Price, Status) values ('Table Cloth 62x114 Colour', 2489405, 1);
insert into Products (Name, Price, Status) values ('Gatorade - Orange', 441683, 1);
insert into Products (Name, Price, Status) values ('Sauce - Oyster', 8221983, 1);
insert into Products (Name, Price, Status) values ('Wine - White, Chardonnay', 9329648, 1);
insert into Products (Name, Price, Status) values ('Sorrel - Fresh', 3063715, 0);
insert into Products (Name, Price, Status) values ('Beef - Top Butt Aaa', 7624043, 0);
insert into Products (Name, Price, Status) values ('Veal - Brisket, Provimi,bnls', 2828647, 1);
insert into Products (Name, Price, Status) values ('Milk - Condensed', 7923247, 0);
insert into Products (Name, Price, Status) values ('Bar - Granola Trail Mix Fruit Nut', 7861432, 1);
insert into Products (Name, Price, Status) values ('Stock - Chicken, White', 3377308, 0);
insert into Products (Name, Price, Status) values ('Energy - Boo - Koo', 6695241, 0);
insert into Products (Name, Price, Status) values ('Nantucket - Pomegranate Pear', 3799420, 0);
insert into Products (Name, Price, Status) values ('Cheese - Boursin, Garlic / Herbs', 3590715, 0);
insert into Products (Name, Price, Status) values ('Bacardi Raspberry', 9657202, 1);
insert into Products (Name, Price, Status) values ('Wine - Semi Dry Riesling Vineland', 5813480, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Iceberg', 4367873, 0);
insert into Products (Name, Price, Status) values ('Versatainer Nc - 8288', 7277534, 1);
insert into Products (Name, Price, Status) values ('Tomatoes Tear Drop Yellow', 9069234, 1);
insert into Products (Name, Price, Status) values ('Beer - True North Strong Ale', 1100353, 0);
insert into Products (Name, Price, Status) values ('Banana - Leaves', 1135290, 1);
insert into Products (Name, Price, Status) values ('Soup - Canadian Pea, Dry Mix', 5546182, 0);
insert into Products (Name, Price, Status) values ('Gatorade - Fruit Punch', 6105512, 0);
insert into Products (Name, Price, Status) values ('Cheese - Ermite Bleu', 9514567, 1);
insert into Products (Name, Price, Status) values ('Cheese Cheddar Processed', 956799, 0);
insert into Products (Name, Price, Status) values ('Nectarines', 3580984, 0);
insert into Products (Name, Price, Status) values ('Compound - Pear', 7611585, 1);
insert into Products (Name, Price, Status) values ('Split Peas - Green, Dry', 3139381, 1);
insert into Products (Name, Price, Status) values ('Pork - Back, Short Cut, Boneless', 1297034, 1);
insert into Products (Name, Price, Status) values ('Flour - All Purpose', 44657, 0);
insert into Products (Name, Price, Status) values ('Cheese - Brick With Pepper', 1308225, 1);
insert into Products (Name, Price, Status) values ('Spring Roll Veg Mini', 134662, 1);
insert into Products (Name, Price, Status) values ('Bagels Poppyseed', 521215, 1);
insert into Products (Name, Price, Status) values ('Lettuce - Sea / Sea Asparagus', 9268341, 1);
insert into Products (Name, Price, Status) values ('Wine - Cotes Du Rhone', 4268718, 0);
insert into Products (Name, Price, Status) values ('Vinegar - Cider', 9073230, 1);
insert into Products (Name, Price, Status) values ('Chocolate Bar - Reese Pieces', 2183368, 1);
insert into Products (Name, Price, Status) values ('Nut - Peanut, Roasted', 7847647, 1);
insert into Products (Name, Price, Status) values ('Squash - Pattypan, Yellow', 8614979, 1);
insert into Products (Name, Price, Status) values ('Smirnoff Green Apple Twist', 6790172, 1);
insert into Products (Name, Price, Status) values ('Godiva White Chocolate', 9953380, 1);
insert into Products (Name, Price, Status) values ('Yogurt - Cherry, 175 Gr', 9730018, 0);
insert into Products (Name, Price, Status) values ('Lettuce - Curly Endive', 8107558, 1);
insert into Products (Name, Price, Status) values ('Soup - Knorr, Ministrone', 2078819, 0);
insert into Products (Name, Price, Status) values ('Cornflakes', 9317416, 1);
insert into Products (Name, Price, Status) values ('Beef - Flank Steak', 215753, 0);
insert into Products (Name, Price, Status) values ('Container - Foam Dixie 12 Oz', 5521038, 0);
insert into Products (Name, Price, Status) values ('Rice - Long Grain', 5506628, 1);
insert into Products (Name, Price, Status) values ('Beef - Outside, Round', 6934542, 1);
insert into Products (Name, Price, Status) values ('Iced Tea - Lemon, 340ml', 7841165, 0);
insert into Products (Name, Price, Status) values ('Ham - Virginia', 2877239, 0);
insert into Products (Name, Price, Status) values ('Seedlings - Clamshell', 808375, 1);
insert into Products (Name, Price, Status) values ('Flour - Corn, Fine', 6089129, 1);
insert into Products (Name, Price, Status) values ('Pepper - Yellow Bell', 1921938, 1);
insert into Products (Name, Price, Status) values ('Energy - Boo - Koo', 1604230, 0);
insert into Products (Name, Price, Status) values ('Chocolate - Pistoles, Lactee, Milk', 2257142, 0);
